### ISSUE TITLE
feat: automate build on every change

### ISSUE THREAD

**Issue by eddiejaoude** [dailydotdev/docs#124]
I think it will be useful to run the `build` command on every change to check the project still works

Example GitHub for the pull request `.github/workflows/build.yml`
```yaml
name: Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
```
