### ISSUE TITLE
BUG: iFrame layout issue

### ISSUE THREAD

**Issue by murtuzaalisurti** [dailydotdev/docs#88]
## Bug
The YouTube video iFrame is not responsive.

## How it looks
![chrome_LIHtGognQc](https://user-images.githubusercontent.com/68743212/179705343-f81d9837-d5c4-4869-8222-29b47ad329e8.jpg)

![chrome_3LQOsbpraJ](https://user-images.githubusercontent.com/68743212/179705548-da4d5af7-2be0-47ba-a476-35757561f992.jpg)

## Solution
Set the height and width of the iFrame like this:

```css
{
    width: 100%;
    height: auto;
    aspect-ratio: 16/9;
}
```

https://user-images.githubusercontent.com/68743212/179706754-f70c1b28-a723-4850-b0f6-dbcfbcb00995.mp4

> I was about to make a PR but I don't know where to add the styles!
